# SpeedLimit by robertlit

# Make sure that this file is in valid YAML format

# 普通飞行的最大速度 (1 meter = 1 block)
max-meters-per-second: 30

# 鞘翅飞行的最大速度 (1 meter = 1 block)
# 设置为 -1 表示不限制鞘翅飞行速度
elytra-max-meters-per-second: 40

# allow players to fall (straight or almost straight) down faster than the speed limit (true = allow, false = don't allow)
allow-falling-bypass: true

# set speed limit mode, if both are true nothing will happen (the default, both are false, means: there is speed limit when flying and also when on ground)
only-flying: false
only-on-ground: false

# 普通飞行超速消息 (accepts color codes) type the message inside the quotes, to disable leave only the quotes with nothing in between
too-fast-message: "&c飞行速度过快，请降低速度。"

# 鞘翅飞行超速消息 (accepts color codes)
elytra-too-fast-message: "&c鞘翅飞行速度过快，请降低速度。"

# whether to set a player back to riding an vehicle after the player passed the speed limit while riding a vehicle
# THIS IS ONLY SUPPORTED IN VERSIONS 1.12 AND ABOVE
put-back-on-vehicle: true

# worlds that have a speed limit
worlds:
- world
- world_nether
- world_the_end

# VL累积系统配置
# 设置为 -1 表示不执行相应操作
vl-system:
  # 普通飞行VL配置
  normal-flying:
    # 累积多少VL后踢出玩家 (-1 = 不踢出)
    kick-threshold: 5
    # 累积多少VL后封禁玩家 (-1 = 不封禁)
    ban-threshold: 10
    # 踢出玩家时执行的命令列表 (使用 {player} 作为玩家名占位符)
    kick-commands:
      - "kick {player} 普通飞行超速违规次数过多"
    # 封禁玩家时执行的命令列表 (使用 {player} 作为玩家名占位符)
    ban-commands:
      - "ban {player} 普通飞行严重超速违规"
      - "broadcast &c玩家 {player} 因普通飞行严重超速违规被封禁"
  
  # 鞘翅飞行VL配置
  elytra-flying:
    # 累积多少VL后踢出玩家 (-1 = 不踢出)
    kick-threshold: 3
    # 累积多少VL后封禁玩家 (-1 = 不封禁)
    ban-threshold: 6
    # 踢出玩家时执行的命令列表 (使用 {player} 作为玩家名占位符)
    kick-commands:
      - "kick {player} 鞘翅飞行超速违规次数过多"
    # 封禁玩家时执行的命令列表 (使用 {player} 作为玩家名占位符)
    ban-commands:
      - "ban {player} 鞘翅飞行严重超速违规"
      - "broadcast &c玩家 {player} 因鞘翅飞行严重超速违规被封禁"
  
  # VL重置时间 (分钟，-1 = 永不重置)
  vl-reset-minutes: 30